version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:12
    container_name: supermetrics
    env_file: .env
    ports:
      - '3000:${PORT}'
    volumes:
      - .:/usr/src/supermetrics
    working_dir: /usr/src/supermetrics
    command: npm start
